-- ============================================================
-- Gallery Migration to Cloudinary - UPDATE statements
-- Generated by scripts/migrate-gallery-to-cloudinary.js
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================================

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625439/tedxdutse/gallery/jxkrmlhybqshqw9qw9ye.jpg',
  public_id    = 'tedxdutse/gallery/jxkrmlhybqshqw9qw9ye',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 184336
WHERE id = 1;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625443/tedxdutse/gallery/a027tuasfhmbjglfk8i8.jpg',
  public_id    = 'tedxdutse/gallery/a027tuasfhmbjglfk8i8',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 455096
WHERE id = 2;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625446/tedxdutse/gallery/dwe9axcyucctnaxi8ard.jpg',
  public_id    = 'tedxdutse/gallery/dwe9axcyucctnaxi8ard',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 560380
WHERE id = 3;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625449/tedxdutse/gallery/kphq5tamoyjhheg0iuqb.jpg',
  public_id    = 'tedxdutse/gallery/kphq5tamoyjhheg0iuqb',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 584275
WHERE id = 4;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625451/tedxdutse/gallery/eys8vxdbiglkrficupsz.jpg',
  public_id    = 'tedxdutse/gallery/eys8vxdbiglkrficupsz',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 254952
WHERE id = 5;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625453/tedxdutse/gallery/n4v4gq43lehvbxgrqrm5.jpg',
  public_id    = 'tedxdutse/gallery/n4v4gq43lehvbxgrqrm5',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 381254
WHERE id = 6;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625455/tedxdutse/gallery/mbb4epwcmaycychbicxk.jpg',
  public_id    = 'tedxdutse/gallery/mbb4epwcmaycychbicxk',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 544232
WHERE id = 7;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625458/tedxdutse/gallery/s2v0otpl9swbsujfmlps.jpg',
  public_id    = 'tedxdutse/gallery/s2v0otpl9swbsujfmlps',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 453495
WHERE id = 8;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625460/tedxdutse/gallery/wlgkxrcr0s6wtutfwube.jpg',
  public_id    = 'tedxdutse/gallery/wlgkxrcr0s6wtutfwube',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 243712
WHERE id = 9;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625462/tedxdutse/gallery/aoiltucfzd1h1currbhv.jpg',
  public_id    = 'tedxdutse/gallery/aoiltucfzd1h1currbhv',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 256519
WHERE id = 10;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625464/tedxdutse/gallery/zixuzrpj6vhpsh5rqme0.jpg',
  public_id    = 'tedxdutse/gallery/zixuzrpj6vhpsh5rqme0',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 271674
WHERE id = 11;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625466/tedxdutse/gallery/n2eg5jw2xtwkvakid6jd.jpg',
  public_id    = 'tedxdutse/gallery/n2eg5jw2xtwkvakid6jd',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 265351
WHERE id = 12;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625468/tedxdutse/gallery/ionv2fsaonn83np2s6xw.jpg',
  public_id    = 'tedxdutse/gallery/ionv2fsaonn83np2s6xw',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 483970
WHERE id = 13;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625475/tedxdutse/gallery/rt78fg3awcjeo9uszwgc.jpg',
  public_id    = 'tedxdutse/gallery/rt78fg3awcjeo9uszwgc',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 2000,
  bytes        = 492155
WHERE id = 14;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625479/tedxdutse/gallery/x8u4gky618vbffp3etkd.jpg',
  public_id    = 'tedxdutse/gallery/x8u4gky618vbffp3etkd',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 224742
WHERE id = 15;

UPDATE gallery_images
SET
  src          = 'https://res.cloudinary.com/dakwilv8p/image/upload/v1779625481/tedxdutse/gallery/w4kfsx14cvqadsnrqjyp.jpg',
  public_id    = 'tedxdutse/gallery/w4kfsx14cvqadsnrqjyp',
  resource_type = 'image',
  format       = 'jpg',
  width        = 1600,
  height       = 1067,
  bytes        = 213573
WHERE id = 16;

-- Verify the migration
SELECT id, src, public_id, format, width, height, bytes
FROM gallery_images
WHERE public_id IS NOT NULL
ORDER BY id;